# Generated by Django 3.1.6 on 2021-02-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='company',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.TextField(max_length=40),
        ),
    ]
