# Generated by Django 3.1.6 on 2021-02-07 23:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_auto_20210207_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
