# Generated by Django 3.1.6 on 2021-02-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_auto_20210207_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userTempId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.tenant')),
            ],
        ),
    ]
