# Generated by Django 3.1.6 on 2021-02-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_auto_20210212_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='Temperature',
            new_name='temperature',
        ),
    ]
