# Generated by Django 3.1.6 on 2021-02-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_auto_20210212_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='temperature',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
