# Generated by Django 3.1.6 on 2021-02-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0009_auto_20210212_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
