# Generated by Django 3.1.6 on 2021-02-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0012_auto_20210212_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
